[package]
name = "Rust-HTTP-WebServer"
version = "0.1.0"
edition = "2024"

[dependencies]
hyper = { version = "0.14", features = ["full", "server"] }
tokio = { version = "1", features = ["full"] }
mime_guess = "2.0"